OfdanSearchBundle_homepage:
    pattern:  /
    defaults: { _controller: OfdanSearchBundle:Static:home }

OfdanSearchBundle_about:
    pattern:  /s/about-us
    defaults: { _controller: OfdanSearchBundle:Static:about }

OfdanSearchBundle_1:
    pattern:  /s/1
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_about
        permanent: true # this for 301

OfdanSearchBundle_license:
    pattern:  /s/license
    defaults: { _controller: OfdanSearchBundle:Static:license }

OfdanSearchBundle_2:
    pattern:  /s/2
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_license
        permanent: true # this for 301
