OfdanSearchBundle_homepage:
    pattern:  /
    defaults: { _controller: OfdanSearchBundle:Static:home }

OfdanSearchBundle_about:
    pattern:  /s/about-us
    defaults: { _controller: OfdanSearchBundle:Static:about }

OfdanSearchBundle_1:
    pattern:  /s/1
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_about
        permanent: true # this for 301

OfdanSearchBundle_license:
    pattern:  /s/license
    defaults: { _controller: OfdanSearchBundle:Static:license }

OfdanSearchBundle_2:
    pattern:  /s/2
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_license
        permanent: true # this for 301

OfdanSearchBundle_download:
    pattern:  /s/download
    defaults: { _controller: OfdanSearchBundle:Static:download }

OfdanSearchBundle_3:
    pattern:  /s/3
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_download
        permanent: true # this for 301

OfdanSearchBundle_spy:
    pattern:  /s/spy
    defaults: { _controller: OfdanSearchBundle:Page:spy }

OfdanSearchBundle_6:
    pattern:  /s/6
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_spy
        permanent: true # this for 301
