OfdanSearchBundle_homepage:
    pattern:  /
    defaults: { _controller: OfdanSearchBundle:Static:home }

OfdanSearchBundle_1:
    pattern:  /pico/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_homepage
        permanent: true # this for 301

OfdanSearchBundle_search:
    pattern:  /search
    defaults: { _controller: OfdanSearchBundle:Search:index }

OfdanSearchBundle_search_with_query:
    pattern:  /search/{query}
    defaults: { _controller: OfdanSearchBundle:Search:index }

OfdanSearchBundle_search_with_query_original:
    pattern:  /q/{query}
    defaults: { _controller: OfdanSearchBundle:Search:index }

OfdanSearchBundle_search_with_query_original_and_slash:
    pattern:  /q/{query}/
    defaults: { _controller: OfdanSearchBundle:Search:index }

OfdanSearchBundle_search_with_query_original_and_page:
    pattern:  /q/{query}/p/{page}
    defaults: { _controller: OfdanSearchBundle:Search:index }
    requirements:
         page:  \d+

OfdanSearchBundle_search_with_query_original_and_page_and_slash:
    pattern:  /q/{query}/p/{page}/
    defaults: { _controller: OfdanSearchBundle:Search:index }
    requirements:
         page:  \d+

OfdanSearchBundle_cache:
    pattern:  /cache
    defaults: { _controller: OfdanSearchBundle:Cache:index }


OfdanSearchBundle_old_cache1:
    pattern:  /pico/cache.php
    defaults: { _controller: OfdanSearchBundle:Cache:index }

OfdanSearchBundle_old_cache2:
    pattern:  /cache.php
    defaults: { _controller: OfdanSearchBundle:Cache:index }


OfdanSearchBundle_about:
    pattern:  /s/about-us
    defaults: { _controller: OfdanSearchBundle:Static:about }

OfdanSearchBundle_1:
    pattern:  /s/1
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_about
        permanent: true # this for 301

OfdanSearchBundle_1s:
    pattern:  /s/1/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_about
        permanent: true # this for 301

OfdanSearchBundle_license:
    pattern:  /s/license
    defaults: { _controller: OfdanSearchBundle:Static:license }

OfdanSearchBundle_2:
    pattern:  /s/2
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_license
        permanent: true # this for 301

OfdanSearchBundle_2s:
    pattern:  /s/2/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_license
        permanent: true # this for 301

OfdanSearchBundle_download:
    pattern:  /s/download
    defaults: { _controller: OfdanSearchBundle:Static:download }

OfdanSearchBundle_3:
    pattern:  /s/3
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_download
        permanent: true # this for 301

OfdanSearchBundle_3s:
    pattern:  /s/3/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_download
        permanent: true # this for 301

OfdanSearchBundle_suggest:
    pattern:  /s/suggest
    defaults: { _controller: OfdanSearchBundle:Page:suggest }

OfdanSearchBundle_suggestionAdded:
    pattern:  /s/suggest/success
    defaults: { _controller: OfdanSearchBundle:Page:suggestionAdded }

OfdanSearchBundle_suggestionExists:
    pattern:  /s/suggest/exists
    defaults: { _controller: OfdanSearchBundle:Page:suggestionExists }

OfdanSearchBundle_4:
    pattern:  /s/4
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_suggest
        permanent: true # this for 301

OfdanSearchBundle_4s:
    pattern:  /s/4/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_suggest
        permanent: true # this for 301

OfdanSearchBundle_statistics:
    pattern:  /s/statistics
    defaults: { _controller: OfdanSearchBundle:Page:statistics }

OfdanSearchBundle_5:
    pattern:  /s/5
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_statistics
        permanent: true # this for 301

OfdanSearchBundle_5s:
    pattern:  /s/5/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_statistics
        permanent: true # this for 301

OfdanSearchBundle_spy:
    pattern:  /s/spy
    defaults: { _controller: OfdanSearchBundle:Page:spy }

OfdanSearchBundle_6:
    pattern:  /s/6
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_spy
        permanent: true # this for 301

OfdanSearchBundle_6s:
    pattern:  /s/6/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_spy
        permanent: true # this for 301

OfdanSearchBundle_words:
    pattern:  /s/words
    defaults: { _controller: OfdanSearchBundle:Page:words }

OfdanSearchBundle_7:
    pattern:  /s/7
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_words
        permanent: true # this for 301

OfdanSearchBundle_7s:
    pattern:  /s/7/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: OfdanSearchBundle_words
        permanent: true # this for 301
