parameters:
#    ofdan_search.example.class: Ofdan\SearchBundle\Example

services:
#    ofdan_search.example:
#        class: %ofdan_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
