SQL now generated by Symfony2

app/console doctrine:database:create
app/console doctrine:schema:update

either append --force or --dump-sql depending on use.

Don't forget to setup parameter.yml
