OfdanCrawlerBundle:
    resource: "@OfdanCrawlerBundle/Resources/config/routing.yml"
    prefix:   /

OfdanSearchBundle:
    resource: "@OfdanSearchBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
